services:
  frontend:
    build:
      context: ./pc
    container_name: mili-frontend
    platform: linux/amd64
    restart: always
    environment:
      PUBLIC_PATH: "//localhost:9906/"
    ports:
      - "9906:9906"
    networks:
      - mili-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9906" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    container_name: mili-web
    platform: linux/amd64
    restart: always
    environment:
      PORT: 9905
      DB_HOST: mysql
      REDIS_HOST: redis
      STATS_D_HOST: graphite
      STATIC_URL: "//localhost:9906"
    ports:
      - "9905:9905"
    networks:
      - mili-network
    depends_on:
      - mysql
      - redis
      - graphite
      - frontend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9905" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:5.6
    container_name: mili-mysql
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${MILI_MYSQL_DB:-mili}
      MYSQL_USER: ${MILI_MYSQL_USER:-mili}
      MYSQL_PASSWORD: ${MILI_MYSQL_PASSWORD:-mili_password}
    ports:
      - "3306:3306"
    volumes:
      - ./runtime/mysql_data:/var/lib/mysql
      - ./sql/init-database:/docker-entrypoint-initdb.d
    networks:
      - mili-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: mili-redis
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis_password}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}
    ports:
      - "6379:6379"
    volumes:
      - ./runtime/redis_data:/data
    networks:
      - mili-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: ops-graphite
    restart: always
    ports:
      - "8880:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    networks:
      - mili-network

  grafana:
    image: grafana/grafana
    container_name: ops-grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - mili-network
    depends_on:
      - graphite
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mili-network:
    driver: bridge
